USE [master]
GO

/****** Object:  Database [RecyclableDB]    Script Date: 5/31/2024 11:58:25 PM ******/
CREATE DATABASE [RecyclableDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RecyclableDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RecyclableDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RecyclableDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\RecyclableDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RecyclableDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RecyclableDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RecyclableDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RecyclableDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RecyclableDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RecyclableDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [RecyclableDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RecyclableDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RecyclableDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RecyclableDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RecyclableDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RecyclableDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RecyclableDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RecyclableDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RecyclableDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RecyclableDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RecyclableDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RecyclableDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RecyclableDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RecyclableDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RecyclableDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RecyclableDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RecyclableDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RecyclableDB] SET RECOVERY FULL 
GO

ALTER DATABASE [RecyclableDB] SET  MULTI_USER 
GO

ALTER DATABASE [RecyclableDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RecyclableDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [RecyclableDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [RecyclableDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [RecyclableDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [RecyclableDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [RecyclableDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [RecyclableDB] SET  READ_WRITE 
GO

